### ISSUE TITLE
Dingo-hat-2-layer power traces too thin

### ISSUE THREAD

**Issue by PCRobert** [CCHS-Melbourne/donkey-hat#13]
0.5mm traces are good to only ~1.5A. Need ~1.5mm for 3A.

**Comment by PCRobert** [comment]
IPC-2221 calculator says 1.37mm will give 10C rise @ 3A.

**Comment by mage0r** [comment]
Switched to 1.37mm in 522ffcd9912a467c827c6267047b75df5bd68a04
